#!/usr/bin/env bash
# Takes domain names and prints out the subdomain's information

domain_info () {
		record_type=$(dig "$2"."$1" +noall +answer | awk '{print $4}')
		ip=$(dig "$2"."$1" +noall +answer | awk '{print $5}')
		printf "The subdomain %s is a %s record and points to %s\n" "$2" "$record_type" "$ip"
}

if [ -z "$2" ]; then
	for sub in "www" "lb-01" "web-01" "web-02"
	do
		domain_info "$1" "$sub"
	done
else
	domain_info "$1" "$2"
fi
