#!/usr/bin/env bash
# Takes domain names and prints out the subdomain's information

domain_info () {
	full="$2.$1"
	dig "$full" +noall +answer | awk -v ans="$2" 'BEGIN{dom=ans} {print "The subdomain "dom" is a "$4" record and points to "$5}'
}

if [ "$#" -eq 1 ]; then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	domain_info "$1" "$2"
fi
