#!/usr/bin/env bash
# Takes domain names and prints out the subdomain's information

domain_info () {
		line=$(dig "$2"."$1" +noall +answer)
		echo "$2 $line" | awk '{print "The subdomain "$1" is a "$5" record and points to "$6}'
}

if [ "$#" -eq 1 ]; then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	domain_info "$1" "$2"
fi
