#!/usr/bin/env bash
# Uses 'scp' command to transfer a file from the current machine to a remote machine

# Gets the number of the arguments passed
num_args=$#

if [ "$num_args" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# Gets the arguments
	src=$1
	host=$2
	user=$3
	private_key=$4
	
	# Check if the file path to the private key was supplied
	if [ -z "$private_key" ]
	then
		scp -o StrictHostKeyChecking=no "$src" "$user"@"$host":~/
	else
		scp -o StrictHostKeyChecking=no -i "$private_key" "$src" "$user"@"$host":~/
	fi
fi
