#!/usr/bin/env bash
# Installs and sets up nginx web server on my server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

config_file="/etc/nginx/sites-available/default"
line_1="\tlocation = /redirect_me/ {"
line_2="\t\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
line_3="\t}"
line_4="\t# pass PHP scripts to FastCGI server"
route_redirect="$line_1\n$line_2\n$line_3\n$line_4"
sudo sed -i "/$line_4/i \ $route_redirect/" "$config_file"

sudo service nginx start
