#!/usr/bin/env bash
# Installs and sets up nginx web server on my server

# Step 1: Update local repos and install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

config_file="/etc/nginx/sites-available/default"
line_1="\tlocation = /redirect_me/ {"
line_2="\t\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
line_3="\t}"
line_4="\t# pass PHP scripts to FastCGI server"
route_redirect="$line_1\n$line_2\n$line_3"
sudo sed -i "/$line_4/i \ $route_redirect" "$config_file"

error_page="/error_page.html"
root_dir="/var/www/html"
full_path="$root_dir$error_page"
echo "Ceci n'est pas une page" > "$full_path"
current="\tserver_name _;"
line_1="\terror_page 404 $error_page;"
line_2="\tlocation = $error_page {"
line_3="\t\troot $root_dir;"
line_4="\t\tinternal;"
line_5="\t}"
append="$line_1\n$line_2\n$line_3\n$line_4\n$line_5"
sudo sed -i "/$current/a \ $append" "$config_file"

hostname=$(hostname)
line="\tindex index.html index.htm index.nginx-debian.html;"
line_after="\tadd_header X-Served-By $hostname;"
sudo sed -i "/$line/a \ $line_after" "$config_file"

sudo service nginx start
