#!/usr/bin/env bash
# Sets up an Nginx server to return a page only on port 80

# Installed Nginx
#sudo apt-get update
#sudo apt-get install -y nginx

# Started the Nginx service
sudo service nginx start
