#!/usr/bin/env bash
# Sets up an Nginx server to return a page only on port 80

sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln --symbolic /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
